title: Magpie Corner
email: c04511234@gmail.com
description: This is where I post some of my drawings!
#baseurl: ''
url: 'https://operating-potato.github.io/birds'
github_username: Operating-Potato
theme: minima
remote-theme: minima
plugins:
  - jekyll-feed
