title: Magpie Corner
email: c04511234@gmail.com
description: This is the bird blog…
author: Charles Ai
baseurl: '/birds'
url: 'https://operating-potato.github.io/birds'
github_username: Operating-Potato
theme: minima
plugins:
  - jekyll-feed
header_pages:
    - about.markdown
    - species/index.md
